name: Release ESP32 CI (NO-VALIDATOR)

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install platformio
          pio --version

      - name: Locate PlatformIO project
        id: pio
        run: |
          FILE="$(git ls-files | grep -m1 -E '^platformio\.ini$|.*/platformio\.ini$' || true)"
          if [ -z "$FILE" ]; then echo "ERROR: platformio.ini not found"; exit 1; fi
          DIR="$(dirname "$FILE")"
          echo "dir=$DIR" >> "$GITHUB_OUTPUT"
          echo "Found platformio.ini at: $DIR"

      - name: Snapshot (tree & platformio.ini)
        working-directory: ${{ steps.pio.outputs.dir }}
        run: |
          mkdir -p __diag__
          (echo "== TREE =="; find . -maxdepth 3 -type f -print) > __diag__/tree.txt
          sed -n '1,200p' platformio.ini > __diag__/platformio_dump.txt

      - name: Upload snapshot (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: project-snapshot
          path: |
            ${{ steps.pio.outputs.dir }}/__diag__/tree.txt
            ${{ steps.pio.outputs.dir }}/__diag__/platformio_dump.txt

      - name: Build firmware (capture log)
        id: build
        working-directory: ${{ steps.pio.outputs.dir }}
        run: |
          ( set -o pipefail; pio run -e full -v |& tee build.log )

      - name: Upload build log (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: ${{ steps.pio.outputs.dir }}/build.log
          if-no-files-found: warn

      - name: Upload .pio/build/full (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pio-build-full
          path: ${{ steps.pio.outputs.dir }}/.pio/build/full/
          if-no-files-found: ignore

      - name: Package firmware
        id: pkg
        working-directory: ${{ steps.pio.outputs.dir }}
        run: |
          OUT=".pio/build/full"
          test -f "$OUT/firmware.bin" || { echo "ERROR: firmware.bin not found at $OUT"; exit 1; }
          mkdir -p dist
          cp "$OUT/firmware.bin"    dist/firmware.bin
          cp "$OUT"/bootloader*.bin dist/bootloader.bin 2>/dev/null || true
          cp "$OUT"/partitions*.bin dist/partitions.bin 2>/dev/null || true
          printf "bootloader.bin @ 0x1000\npartitions.bin @ 0x8000\nfirmware.bin   @ 0x10000\n" > dist/offsets.txt
          (cd dist && sha256sum * > SHA256SUMS.txt)
          ZIP="firmware_${GITHUB_REF_NAME#refs/tags/}.zip"
          (cd dist && zip -9 "../$ZIP" *)
          echo "zipname=$ZIP" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Firmware ${{ github.ref_name }} (NO-VALIDATOR)
          files: |
            ${{ steps.pio.outputs.dir }}/${{ steps.pkg.outputs.zipname }}
            ${{ steps.pio.outputs.dir }}/dist/SHA256SUMS.txt
