name: Release ESP32 CI

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install platformio

      - name: Locate PlatformIO project
        id: pio
        shell: bash
        run: |
          FILE="$(git ls-files | grep -m1 -E '^platformio\.ini$|.*/platformio\.ini$' || true)"
          if [ -z "$FILE" ]; then echo "ERROR: platformio.ini not found"; exit 1; fi
          DIR="$(dirname "$FILE")"
          echo "dir=$DIR" >> "$GITHUB_OUTPUT"
          echo "Found platformio.ini at: $DIR"

      - name: Build (capture log)
        working-directory: ${{ steps.pio.outputs.dir }}
        shell: bash
        run: |
          set -e
          ( set -o pipefail; pio run -e full -v |& tee build.log )

      - name: Upload build log (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: ${{ steps.pio.outputs.dir }}/build.log
          retention-days: 7

      - name: Package
        id: pkg
        working-directory: ${{ steps.pio.outputs.dir }}
        shell: bash
        run: |
          set -e
          OUT=".pio/build/full"
          test -f "$OUT/firmware.bin" || { echo "ERROR: firmware.bin not found at $OUT"; exit 1; }
          mkdir -p dist
          cp "$OUT/firmware.bin"    dist/firmware.bin
          cp "$OUT"/bootloader*.bin dist/bootloader.bin 2>/dev/null || true
          cp "$OUT"/partitions*.bin dist/partitions.bin 2>/dev/null || true
          printf "bootloader.bin @ 0x1000\npartitions.bin @ 0x8000\nfirmware.bin   @ 0x10000\n" > dist/offsets.txt
          (cd dist && sha256sum * > SHA256SUMS.txt)
          ZIP="firmware_${GITHUB_REF_NAME#refs/tags/}.zip"
          (cd dist && zip -9 "../$ZIP" *)
          echo "zipname=$ZIP" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Firmware ${{ github.ref_name }}
          files: |
            ${{ steps.pio.outputs.dir }}/${{ steps.pkg.outputs.zipname }}
            ${{ steps.pio.outputs.dir }}/dist/SHA256SUMS.txt
